# Generated by Django 5.1.1 on 2024-10-21 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerrequest', '0010_remove_customerrequests_facility_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityHasAppLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_store_link', models.CharField(max_length=500)),
                ('app_store_link', models.CharField(max_length=500)),
                ('deep_link', models.CharField(max_length=500)),
                ('short_play_store_link', models.CharField(max_length=500)),
                ('short_app_store_link', models.CharField(max_length=500)),
                ('short_deep_link', models.CharField(max_length=500)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerrequest.facilitymaster')),
            ],
        ),
    ]
