# Generated by Django 5.1.1 on 2024-10-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerrequest', '0010_remove_customerrequests_facility_id_and_more'),
        ('facilitylinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacilityHasAppLinks',
            new_name='FacilityHasAppLink',
        ),
    ]
