# Generated by Django 5.1.1 on 2024-10-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilitylinks', '0002_rename_facilityhasapplinks_facilityhasapplink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityhasapplink',
            name='facility_id',
        ),
    ]
