# Generated by Django 5.1.1 on 2024-10-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequestHasStatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_req_status_type_code', models.CharField(max_length=100)),
                ('cust_req_status_type_name', models.CharField(max_length=200)),
                ('crt_date', models.TimeField(auto_now=True)),
                ('crt_rsn', models.CharField(max_length=100)),
                ('crt_by', models.CharField(max_length=100)),
                ('upd_date', models.TimeField(auto_now=True, null=True)),
                ('upd_rsn', models.CharField(blank=True, max_length=100, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_req_code', models.CharField(max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('request_json', models.TextField(max_length=4294967295)),
                ('crt_date', models.DateTimeField(auto_now=True)),
                ('crt_rsn', models.CharField(max_length=100)),
                ('crt_by', models.CharField(max_length=100)),
                ('upd_date', models.DateTimeField(auto_now=True, null=True)),
                ('upd_rsn', models.CharField(blank=True, max_length=100, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRequestTypeDefn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_req_type_code', models.CharField(max_length=100)),
                ('cust_req_type_name', models.CharField(max_length=200)),
                ('column_description', models.TextField(max_length=4294967295)),
                ('crt_date', models.TimeField(auto_now=True)),
                ('crt_rsn', models.CharField(max_length=100)),
                ('crt_by', models.CharField(max_length=100)),
                ('upd_date', models.TimeField(auto_now=True, null=True)),
                ('upd_rsn', models.CharField(blank=True, max_length=100, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_code', models.CharField(max_length=20)),
                ('facility_name', models.CharField(max_length=500)),
                ('crt_date', models.DateTimeField(auto_now=True)),
                ('crt_rsn', models.CharField(max_length=100)),
                ('crt_by', models.CharField(max_length=100)),
                ('upd_date', models.DateTimeField(auto_now=True, null=True)),
                ('upd_rsn', models.CharField(blank=True, max_length=100, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityTypeDefn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type_code', models.CharField(max_length=20)),
                ('facility_type_name', models.CharField(max_length=100)),
                ('facility_type_desc', models.CharField(max_length=500)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('crt_date', models.DateTimeField(auto_now=True)),
                ('crt_rsn', models.CharField(max_length=100)),
                ('crt_by', models.CharField(max_length=100)),
                ('upd_date', models.DateTimeField(auto_now=True, null=True)),
                ('upd_rsn', models.CharField(blank=True, max_length=100, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityHasAppLink',
            fields=[
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customerrequest.facilitymaster')),
                ('play_store_link', models.CharField(max_length=500)),
                ('app_store_link', models.CharField(max_length=500)),
                ('deep_link', models.CharField(max_length=500)),
                ('short_play_store_link', models.CharField(max_length=500)),
                ('short_app_store_link', models.CharField(max_length=500)),
                ('short_deep_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityHasRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_req_type_code', models.CharField(max_length=100)),
                ('facility_req_type_name', models.CharField(max_length=200)),
                ('crt_date', models.TimeField(auto_now=True)),
                ('crt_rsn', models.CharField(max_length=100)),
                ('crt_by', models.CharField(max_length=100)),
                ('upd_date', models.TimeField(auto_now=True, null=True)),
                ('upd_rsn', models.CharField(blank=True, max_length=100, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_req_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerrequest.customerrequesttypedefn')),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerrequest.facilitymaster')),
            ],
        ),
        migrations.AddField(
            model_name='facilitymaster',
            name='facility_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerrequest.facilitytypedefn'),
        ),
        migrations.CreateModel(
            name='PersonMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_code', models.CharField(max_length=50)),
                ('salutation', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('age_category', models.CharField(max_length=20)),
                ('birth_date', models.DateTimeField()),
                ('resident_flag', models.CharField(max_length=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('crt_date', models.DateTimeField(auto_now=True)),
                ('crt_rsn', models.CharField(max_length=100)),
                ('crt_by', models.CharField(max_length=100)),
                ('upd_date', models.DateTimeField(auto_now=True, null=True)),
                ('upd_rsn', models.CharField(blank=True, max_length=100, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerrequest.facilitymaster')),
            ],
        ),
        migrations.CreateModel(
            name='UnitMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=200)),
                ('extension_no', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('crt_date', models.DateTimeField(auto_now=True)),
                ('crt_rsn', models.CharField(max_length=100)),
                ('crt_by', models.CharField(max_length=100)),
                ('upd_date', models.DateTimeField(auto_now=True, null=True)),
                ('upd_rsn', models.CharField(blank=True, max_length=100, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerrequest.facilitymaster')),
            ],
        ),
    ]
