# Generated by Django 5.1.1 on 2024-10-25 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitymaster',
            name='facility_has_app_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='app_links', to='customerrequest.facilityhasapplink'),
        ),
    ]
